config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'

  resource :sessions, :only => :destroy
  resources :listings

  root 'welcome#index'
end

app/models/listing.rb
class Listing
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :description
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :facebook_id
  field :first_name
  field :last_name

  def self.find_or_create_by_auth_hash(auth_hash)
    params =  { :facebook_id => auth_hash.uid }
    where(params).first || create(params.merge({ :first_name => auth_hash.info.first_name, :last_name => auth_hash.info.last_name }))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:current_user]) if session[:current_user]
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
  end

  def new
    @listing = Listing.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    sign_in User.find_or_create_by_auth_hash(auth_hash)
    redirect_to root_path
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def sign_in(user)
    session[:current_user] = user.id.to_s
  end

  def sign_out
    session.delete(:current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Houseshare
    = stylesheet_link_tag    'application', :media => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      - if logged_in?
        %ul
          %li= current_user.first_name
          %li= link_to('Logout', sessions_path, :method => :delete)
          %li= link_to('Listings', listings_path)
      - else
        = link_to('Login', '/auth/facebook')

    .container
      = yield

app/views/listings/_form.haml
= simple_form_for(listing) do |f|
  = f.error_notification
  = f.input :name
  = f.input :description

app/views/listings/index.haml
= link_to 'New', new_listing_path

app/views/listings/new.haml
%section.container
  .row
    .col-xs-12
      %h2 New Listing
  .row
    .col-xs-12
      = render 'form', :listing => @listing